spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  session:
    store-type: redis
    redis:
      namespace: myapp:session

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

junit.jupiter.execution.parallel:
    enabled: true