spring:
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml
    default-schema: schema
    liquibase-schema: my_liquibase_schema
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

application:
  default-bucket-name: user-files
server:
  servlet:
    session:
      timeout: 1800

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: false
    disable-swagger-default-url: true